// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpdatePolicyService.Models.Database;

#nullable disable

namespace UpdatePolicyService.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241124162340_Create_TablePolicy")]
    partial class Create_TablePolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UpdatePolicyService.Models.Database.TablePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CompletedPrint")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_dat");

                    b.Property<int>("Endcnt")
                        .HasColumnType("int");

                    b.Property<int>("EndorseCount")
                        .HasColumnType("int");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rencnt")
                        .HasColumnType("int");

                    b.Property<bool>("StaPrint")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sta_print");

                    b.Property<bool>("StaRelease")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sta_release");

                    b.HasKey("Id");

                    b.ToTable("TablePolicy", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
